version: '3.3'
services:
  mysql:
    container_name : mysql_symfony
    image: mysql:8.0
    restart: on-failure
    command:
      - "--default-authentication-plugin=mysql_native_password"
    volumes:
      - data-symfony:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  pma:
    container_name : pma_symfony
    image: phpmyadmin
    restart: on-failure
    ports:
      - '${PMA_PORT}:80'
    environment:
      PMA_HOST: mysql_symfony
    depends_on:
      - mysql
  php:
    container_name : php_symfony
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './apps/:/var/www/html'
    ports:
      - '${APACHE_PORT}:80'
      - '443:443'
    restart: on-failure
    depends_on:
      - mysql
volumes:
  data-symfony: