version: '3.3'
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: photodec
      MYSQL_USER: photodec
      MYSQL_PASSWORD: admin
  pma:
    image: phpmyadmin
    restart: on-failure
    ports:
      - '8000:80'
    environment:
      PMA_HOST: mysql
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './apps/:/var/www/html'
    ports:
      - '80:80'
      - '443:443'
    restart: on-failure